# Generated by Django 4.1.3 on 2022-12-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FurnaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataTime', models.TimeField()),
                ('data', models.IntegerField(default=0)),
            ],
        ),
    ]
